//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VkBlendOp {
  VK_BLEND_OP_ADD = 0,
  VK_BLEND_OP_SUBTRACT = 1,
  VK_BLEND_OP_REVERSE_SUBTRACT = 2,
  VK_BLEND_OP_MIN = 3,
  VK_BLEND_OP_MAX = 4,
  VK_BLEND_OP_BEGIN_RANGE = VK_BLEND_OP_ADD,
  VK_BLEND_OP_END_RANGE = VK_BLEND_OP_MAX,
  VK_BLEND_OP_RANGE_SIZE = (VK_BLEND_OP_MAX-VK_BLEND_OP_ADD+1),
  VK_BLEND_OP_MAX_ENUM = 0x7FFFFFFF
}
