//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VkBufferCreateFlagBits {
  VK_BUFFER_CREATE_SPARSE_BINDING_BIT = 0x00000001,
  VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT = 0x00000002,
  VK_BUFFER_CREATE_SPARSE_ALIASED_BIT = 0x00000004
}
