//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkClearValue : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkClearValue(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkClearValue obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkClearValue() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkClearValue(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VkClearColorValue color {
    set {
      vulkanPINVOKE.VkClearValue_color_set(swigCPtr, VkClearColorValue.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkClearValue_color_get(swigCPtr);
      VkClearColorValue ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkClearColorValue(cPtr, false);
      return ret;
    } 
  }

  public VkClearDepthStencilValue depthStencil {
    set {
      vulkanPINVOKE.VkClearValue_depthStencil_set(swigCPtr, VkClearDepthStencilValue.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkClearValue_depthStencil_get(swigCPtr);
      VkClearDepthStencilValue ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkClearDepthStencilValue(cPtr, false);
      return ret;
    } 
  }

  public VkClearValue() : this(vulkanPINVOKE.new_VkClearValue(), true) {
  }

}
