//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkComponentMapping : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkComponentMapping(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkComponentMapping obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkComponentMapping() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkComponentMapping(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VkComponentSwizzle r {
    set {
      vulkanPINVOKE.VkComponentMapping_r_set(swigCPtr, (int)value);
    } 
    get {
      VkComponentSwizzle ret = (VkComponentSwizzle)vulkanPINVOKE.VkComponentMapping_r_get(swigCPtr);
      return ret;
    } 
  }

  public VkComponentSwizzle g {
    set {
      vulkanPINVOKE.VkComponentMapping_g_set(swigCPtr, (int)value);
    } 
    get {
      VkComponentSwizzle ret = (VkComponentSwizzle)vulkanPINVOKE.VkComponentMapping_g_get(swigCPtr);
      return ret;
    } 
  }

  public VkComponentSwizzle b {
    set {
      vulkanPINVOKE.VkComponentMapping_b_set(swigCPtr, (int)value);
    } 
    get {
      VkComponentSwizzle ret = (VkComponentSwizzle)vulkanPINVOKE.VkComponentMapping_b_get(swigCPtr);
      return ret;
    } 
  }

  public VkComponentSwizzle a {
    set {
      vulkanPINVOKE.VkComponentMapping_a_set(swigCPtr, (int)value);
    } 
    get {
      VkComponentSwizzle ret = (VkComponentSwizzle)vulkanPINVOKE.VkComponentMapping_a_get(swigCPtr);
      return ret;
    } 
  }

  public VkComponentMapping() : this(vulkanPINVOKE.new_VkComponentMapping(), true) {
  }

}
