//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VkCompareOp {
  VK_COMPARE_OP_NEVER = 0,
  VK_COMPARE_OP_LESS = 1,
  VK_COMPARE_OP_EQUAL = 2,
  VK_COMPARE_OP_LESS_OR_EQUAL = 3,
  VK_COMPARE_OP_GREATER = 4,
  VK_COMPARE_OP_NOT_EQUAL = 5,
  VK_COMPARE_OP_GREATER_OR_EQUAL = 6,
  VK_COMPARE_OP_ALWAYS = 7,
  VK_COMPARE_OP_BEGIN_RANGE = VK_COMPARE_OP_NEVER,
  VK_COMPARE_OP_END_RANGE = VK_COMPARE_OP_ALWAYS,
  VK_COMPARE_OP_RANGE_SIZE = (VK_COMPARE_OP_ALWAYS-VK_COMPARE_OP_NEVER+1),
  VK_COMPARE_OP_MAX_ENUM = 0x7FFFFFFF
}
