//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkDisplaySurfaceCreateInfoKHR : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkDisplaySurfaceCreateInfoKHR(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkDisplaySurfaceCreateInfoKHR obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkDisplaySurfaceCreateInfoKHR() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkDisplaySurfaceCreateInfoKHR(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VkStructureType sType {
    set {
      vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_sType_set(swigCPtr, (int)value);
    } 
    get {
      VkStructureType ret = (VkStructureType)vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_sType_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void pNext {
    set {
      vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_pNext_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_pNext_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t flags {
    set {
      vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_flags_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_flags_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t displayMode {
    set {
      vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_displayMode_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64_t ret = new SWIGTYPE_p_uint64_t(vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_displayMode_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t planeIndex {
    set {
      vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_planeIndex_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_planeIndex_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t planeStackIndex {
    set {
      vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_planeStackIndex_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_planeStackIndex_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkSurfaceTransformFlagBitsKHR transform {
    set {
      vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_transform_set(swigCPtr, (int)value);
    } 
    get {
      VkSurfaceTransformFlagBitsKHR ret = (VkSurfaceTransformFlagBitsKHR)vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_transform_get(swigCPtr);
      return ret;
    } 
  }

  public float globalAlpha {
    set {
      vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_globalAlpha_set(swigCPtr, value);
    } 
    get {
      float ret = vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_globalAlpha_get(swigCPtr);
      return ret;
    } 
  }

  public VkDisplayPlaneAlphaFlagBitsKHR alphaMode {
    set {
      vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_alphaMode_set(swigCPtr, (int)value);
    } 
    get {
      VkDisplayPlaneAlphaFlagBitsKHR ret = (VkDisplayPlaneAlphaFlagBitsKHR)vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_alphaMode_get(swigCPtr);
      return ret;
    } 
  }

  public VkExtent2D imageExtent {
    set {
      vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_imageExtent_set(swigCPtr, VkExtent2D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkDisplaySurfaceCreateInfoKHR_imageExtent_get(swigCPtr);
      VkExtent2D ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkExtent2D(cPtr, false);
      return ret;
    } 
  }

  public VkDisplaySurfaceCreateInfoKHR() : this(vulkanPINVOKE.new_VkDisplaySurfaceCreateInfoKHR(), true) {
  }

}
