//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkImageMemoryBarrier : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkImageMemoryBarrier(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkImageMemoryBarrier obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkImageMemoryBarrier() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkImageMemoryBarrier(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VkStructureType sType {
    set {
      vulkanPINVOKE.VkImageMemoryBarrier_sType_set(swigCPtr, (int)value);
    } 
    get {
      VkStructureType ret = (VkStructureType)vulkanPINVOKE.VkImageMemoryBarrier_sType_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void pNext {
    set {
      vulkanPINVOKE.VkImageMemoryBarrier_pNext_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkImageMemoryBarrier_pNext_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t srcAccessMask {
    set {
      vulkanPINVOKE.VkImageMemoryBarrier_srcAccessMask_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkImageMemoryBarrier_srcAccessMask_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t dstAccessMask {
    set {
      vulkanPINVOKE.VkImageMemoryBarrier_dstAccessMask_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkImageMemoryBarrier_dstAccessMask_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkImageLayout oldLayout {
    set {
      vulkanPINVOKE.VkImageMemoryBarrier_oldLayout_set(swigCPtr, (int)value);
    } 
    get {
      VkImageLayout ret = (VkImageLayout)vulkanPINVOKE.VkImageMemoryBarrier_oldLayout_get(swigCPtr);
      return ret;
    } 
  }

  public VkImageLayout newLayout {
    set {
      vulkanPINVOKE.VkImageMemoryBarrier_newLayout_set(swigCPtr, (int)value);
    } 
    get {
      VkImageLayout ret = (VkImageLayout)vulkanPINVOKE.VkImageMemoryBarrier_newLayout_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t srcQueueFamilyIndex {
    set {
      vulkanPINVOKE.VkImageMemoryBarrier_srcQueueFamilyIndex_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkImageMemoryBarrier_srcQueueFamilyIndex_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t dstQueueFamilyIndex {
    set {
      vulkanPINVOKE.VkImageMemoryBarrier_dstQueueFamilyIndex_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkImageMemoryBarrier_dstQueueFamilyIndex_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t image {
    set {
      vulkanPINVOKE.VkImageMemoryBarrier_image_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64_t ret = new SWIGTYPE_p_uint64_t(vulkanPINVOKE.VkImageMemoryBarrier_image_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkImageSubresourceRange subresourceRange {
    set {
      vulkanPINVOKE.VkImageMemoryBarrier_subresourceRange_set(swigCPtr, VkImageSubresourceRange.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkImageMemoryBarrier_subresourceRange_get(swigCPtr);
      VkImageSubresourceRange ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkImageSubresourceRange(cPtr, false);
      return ret;
    } 
  }

  public VkImageMemoryBarrier() : this(vulkanPINVOKE.new_VkImageMemoryBarrier(), true) {
  }

}
