//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkImageCopy : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkImageCopy(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkImageCopy obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkImageCopy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkImageCopy(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VkImageSubresourceLayers srcSubresource {
    set {
      vulkanPINVOKE.VkImageCopy_srcSubresource_set(swigCPtr, VkImageSubresourceLayers.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkImageCopy_srcSubresource_get(swigCPtr);
      VkImageSubresourceLayers ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkImageSubresourceLayers(cPtr, false);
      return ret;
    } 
  }

  public VkOffset3D srcOffset {
    set {
      vulkanPINVOKE.VkImageCopy_srcOffset_set(swigCPtr, VkOffset3D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkImageCopy_srcOffset_get(swigCPtr);
      VkOffset3D ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkOffset3D(cPtr, false);
      return ret;
    } 
  }

  public VkImageSubresourceLayers dstSubresource {
    set {
      vulkanPINVOKE.VkImageCopy_dstSubresource_set(swigCPtr, VkImageSubresourceLayers.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkImageCopy_dstSubresource_get(swigCPtr);
      VkImageSubresourceLayers ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkImageSubresourceLayers(cPtr, false);
      return ret;
    } 
  }

  public VkOffset3D dstOffset {
    set {
      vulkanPINVOKE.VkImageCopy_dstOffset_set(swigCPtr, VkOffset3D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkImageCopy_dstOffset_get(swigCPtr);
      VkOffset3D ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkOffset3D(cPtr, false);
      return ret;
    } 
  }

  public VkExtent3D extent {
    set {
      vulkanPINVOKE.VkImageCopy_extent_set(swigCPtr, VkExtent3D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkImageCopy_extent_get(swigCPtr);
      VkExtent3D ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkExtent3D(cPtr, false);
      return ret;
    } 
  }

  public VkImageCopy() : this(vulkanPINVOKE.new_VkImageCopy(), true) {
  }

}
