//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VkImageAspectFlagBits {
  VK_IMAGE_ASPECT_COLOR_BIT = 0x00000001,
  VK_IMAGE_ASPECT_DEPTH_BIT = 0x00000002,
  VK_IMAGE_ASPECT_STENCIL_BIT = 0x00000004,
  VK_IMAGE_ASPECT_METADATA_BIT = 0x00000008
}
