//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VkImageType {
  VK_IMAGE_TYPE_1D = 0,
  VK_IMAGE_TYPE_2D = 1,
  VK_IMAGE_TYPE_3D = 2,
  VK_IMAGE_TYPE_BEGIN_RANGE = VK_IMAGE_TYPE_1D,
  VK_IMAGE_TYPE_END_RANGE = VK_IMAGE_TYPE_3D,
  VK_IMAGE_TYPE_RANGE_SIZE = (VK_IMAGE_TYPE_3D-VK_IMAGE_TYPE_1D+1),
  VK_IMAGE_TYPE_MAX_ENUM = 0x7FFFFFFF
}
