//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VkImageUsageFlagBits {
  VK_IMAGE_USAGE_TRANSFER_SRC_BIT = 0x00000001,
  VK_IMAGE_USAGE_TRANSFER_DST_BIT = 0x00000002,
  VK_IMAGE_USAGE_SAMPLED_BIT = 0x00000004,
  VK_IMAGE_USAGE_STORAGE_BIT = 0x00000008,
  VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT = 0x00000010,
  VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 0x00000020,
  VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT = 0x00000040,
  VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT = 0x00000080
}
