//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkImageViewCreateInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkImageViewCreateInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkImageViewCreateInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkImageViewCreateInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkImageViewCreateInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VkStructureType sType {
    set {
      vulkanPINVOKE.VkImageViewCreateInfo_sType_set(swigCPtr, (int)value);
    } 
    get {
      VkStructureType ret = (VkStructureType)vulkanPINVOKE.VkImageViewCreateInfo_sType_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void pNext {
    set {
      vulkanPINVOKE.VkImageViewCreateInfo_pNext_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkImageViewCreateInfo_pNext_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t flags {
    set {
      vulkanPINVOKE.VkImageViewCreateInfo_flags_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkImageViewCreateInfo_flags_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t image {
    set {
      vulkanPINVOKE.VkImageViewCreateInfo_image_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64_t ret = new SWIGTYPE_p_uint64_t(vulkanPINVOKE.VkImageViewCreateInfo_image_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkImageViewType viewType {
    set {
      vulkanPINVOKE.VkImageViewCreateInfo_viewType_set(swigCPtr, (int)value);
    } 
    get {
      VkImageViewType ret = (VkImageViewType)vulkanPINVOKE.VkImageViewCreateInfo_viewType_get(swigCPtr);
      return ret;
    } 
  }

  public VkFormat format {
    set {
      vulkanPINVOKE.VkImageViewCreateInfo_format_set(swigCPtr, (int)value);
    } 
    get {
      VkFormat ret = (VkFormat)vulkanPINVOKE.VkImageViewCreateInfo_format_get(swigCPtr);
      return ret;
    } 
  }

  public VkComponentMapping components {
    set {
      vulkanPINVOKE.VkImageViewCreateInfo_components_set(swigCPtr, VkComponentMapping.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkImageViewCreateInfo_components_get(swigCPtr);
      VkComponentMapping ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkComponentMapping(cPtr, false);
      return ret;
    } 
  }

  public VkImageSubresourceRange subresourceRange {
    set {
      vulkanPINVOKE.VkImageViewCreateInfo_subresourceRange_set(swigCPtr, VkImageSubresourceRange.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkImageViewCreateInfo_subresourceRange_get(swigCPtr);
      VkImageSubresourceRange ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkImageSubresourceRange(cPtr, false);
      return ret;
    } 
  }

  public VkImageViewCreateInfo() : this(vulkanPINVOKE.new_VkImageViewCreateInfo(), true) {
  }

}
