//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VkIndexType {
  VK_INDEX_TYPE_UINT16 = 0,
  VK_INDEX_TYPE_UINT32 = 1,
  VK_INDEX_TYPE_BEGIN_RANGE = VK_INDEX_TYPE_UINT16,
  VK_INDEX_TYPE_END_RANGE = VK_INDEX_TYPE_UINT32,
  VK_INDEX_TYPE_RANGE_SIZE = (VK_INDEX_TYPE_UINT32-VK_INDEX_TYPE_UINT16+1),
  VK_INDEX_TYPE_MAX_ENUM = 0x7FFFFFFF
}
