//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkPhysicalDeviceProperties : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkPhysicalDeviceProperties(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkPhysicalDeviceProperties obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkPhysicalDeviceProperties() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkPhysicalDeviceProperties(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_uint32_t apiVersion {
    set {
      vulkanPINVOKE.VkPhysicalDeviceProperties_apiVersion_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPhysicalDeviceProperties_apiVersion_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t driverVersion {
    set {
      vulkanPINVOKE.VkPhysicalDeviceProperties_driverVersion_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPhysicalDeviceProperties_driverVersion_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t vendorID {
    set {
      vulkanPINVOKE.VkPhysicalDeviceProperties_vendorID_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPhysicalDeviceProperties_vendorID_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t deviceID {
    set {
      vulkanPINVOKE.VkPhysicalDeviceProperties_deviceID_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPhysicalDeviceProperties_deviceID_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkPhysicalDeviceType deviceType {
    set {
      vulkanPINVOKE.VkPhysicalDeviceProperties_deviceType_set(swigCPtr, (int)value);
    } 
    get {
      VkPhysicalDeviceType ret = (VkPhysicalDeviceType)vulkanPINVOKE.VkPhysicalDeviceProperties_deviceType_get(swigCPtr);
      return ret;
    } 
  }

  public string deviceName {
    set {
      vulkanPINVOKE.VkPhysicalDeviceProperties_deviceName_set(swigCPtr, value);
    } 
    get {
      string ret = vulkanPINVOKE.VkPhysicalDeviceProperties_deviceName_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint8_t pipelineCacheUUID {
    set {
      vulkanPINVOKE.VkPhysicalDeviceProperties_pipelineCacheUUID_set(swigCPtr, SWIGTYPE_p_uint8_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPhysicalDeviceProperties_pipelineCacheUUID_get(swigCPtr);
      SWIGTYPE_p_uint8_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
      return ret;
    } 
  }

  public VkPhysicalDeviceLimits limits {
    set {
      vulkanPINVOKE.VkPhysicalDeviceProperties_limits_set(swigCPtr, VkPhysicalDeviceLimits.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPhysicalDeviceProperties_limits_get(swigCPtr);
      VkPhysicalDeviceLimits ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkPhysicalDeviceLimits(cPtr, false);
      return ret;
    } 
  }

  public VkPhysicalDeviceSparseProperties sparseProperties {
    set {
      vulkanPINVOKE.VkPhysicalDeviceProperties_sparseProperties_set(swigCPtr, VkPhysicalDeviceSparseProperties.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPhysicalDeviceProperties_sparseProperties_get(swigCPtr);
      VkPhysicalDeviceSparseProperties ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkPhysicalDeviceSparseProperties(cPtr, false);
      return ret;
    } 
  }

  public VkPhysicalDeviceProperties() : this(vulkanPINVOKE.new_VkPhysicalDeviceProperties(), true) {
  }

}
