//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkPhysicalDeviceMemoryProperties : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkPhysicalDeviceMemoryProperties(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkPhysicalDeviceMemoryProperties obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkPhysicalDeviceMemoryProperties() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkPhysicalDeviceMemoryProperties(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_uint32_t memoryTypeCount {
    set {
      vulkanPINVOKE.VkPhysicalDeviceMemoryProperties_memoryTypeCount_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPhysicalDeviceMemoryProperties_memoryTypeCount_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkMemoryType memoryTypes {
    set {
      vulkanPINVOKE.VkPhysicalDeviceMemoryProperties_memoryTypes_set(swigCPtr, VkMemoryType.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPhysicalDeviceMemoryProperties_memoryTypes_get(swigCPtr);
      VkMemoryType ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkMemoryType(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t memoryHeapCount {
    set {
      vulkanPINVOKE.VkPhysicalDeviceMemoryProperties_memoryHeapCount_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPhysicalDeviceMemoryProperties_memoryHeapCount_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkMemoryHeap memoryHeaps {
    set {
      vulkanPINVOKE.VkPhysicalDeviceMemoryProperties_memoryHeaps_set(swigCPtr, VkMemoryHeap.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPhysicalDeviceMemoryProperties_memoryHeaps_get(swigCPtr);
      VkMemoryHeap ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkMemoryHeap(cPtr, false);
      return ret;
    } 
  }

  public VkPhysicalDeviceMemoryProperties() : this(vulkanPINVOKE.new_VkPhysicalDeviceMemoryProperties(), true) {
  }

}
