//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkPipelineDepthStencilStateCreateInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkPipelineDepthStencilStateCreateInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkPipelineDepthStencilStateCreateInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkPipelineDepthStencilStateCreateInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkPipelineDepthStencilStateCreateInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VkStructureType sType {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_sType_set(swigCPtr, (int)value);
    } 
    get {
      VkStructureType ret = (VkStructureType)vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_sType_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void pNext {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_pNext_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_pNext_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t flags {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_flags_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_flags_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t depthTestEnable {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_depthTestEnable_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_depthTestEnable_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t depthWriteEnable {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_depthWriteEnable_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_depthWriteEnable_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkCompareOp depthCompareOp {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_depthCompareOp_set(swigCPtr, (int)value);
    } 
    get {
      VkCompareOp ret = (VkCompareOp)vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_depthCompareOp_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t depthBoundsTestEnable {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_depthBoundsTestEnable_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_depthBoundsTestEnable_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t stencilTestEnable {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_stencilTestEnable_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_stencilTestEnable_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkStencilOpState front {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_front_set(swigCPtr, VkStencilOpState.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_front_get(swigCPtr);
      VkStencilOpState ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkStencilOpState(cPtr, false);
      return ret;
    } 
  }

  public VkStencilOpState back {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_back_set(swigCPtr, VkStencilOpState.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_back_get(swigCPtr);
      VkStencilOpState ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkStencilOpState(cPtr, false);
      return ret;
    } 
  }

  public float minDepthBounds {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_minDepthBounds_set(swigCPtr, value);
    } 
    get {
      float ret = vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_minDepthBounds_get(swigCPtr);
      return ret;
    } 
  }

  public float maxDepthBounds {
    set {
      vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_maxDepthBounds_set(swigCPtr, value);
    } 
    get {
      float ret = vulkanPINVOKE.VkPipelineDepthStencilStateCreateInfo_maxDepthBounds_get(swigCPtr);
      return ret;
    } 
  }

  public VkPipelineDepthStencilStateCreateInfo() : this(vulkanPINVOKE.new_VkPipelineDepthStencilStateCreateInfo(), true) {
  }

}
