//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VkPolygonMode {
  VK_POLYGON_MODE_FILL = 0,
  VK_POLYGON_MODE_LINE = 1,
  VK_POLYGON_MODE_POINT = 2,
  VK_POLYGON_MODE_BEGIN_RANGE = VK_POLYGON_MODE_FILL,
  VK_POLYGON_MODE_END_RANGE = VK_POLYGON_MODE_POINT,
  VK_POLYGON_MODE_RANGE_SIZE = (VK_POLYGON_MODE_POINT-VK_POLYGON_MODE_FILL+1),
  VK_POLYGON_MODE_MAX_ENUM = 0x7FFFFFFF
}
