//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkPresentInfoKHR : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkPresentInfoKHR(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkPresentInfoKHR obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkPresentInfoKHR() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkPresentInfoKHR(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VkStructureType sType {
    set {
      vulkanPINVOKE.VkPresentInfoKHR_sType_set(swigCPtr, (int)value);
    } 
    get {
      VkStructureType ret = (VkStructureType)vulkanPINVOKE.VkPresentInfoKHR_sType_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void pNext {
    set {
      vulkanPINVOKE.VkPresentInfoKHR_pNext_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPresentInfoKHR_pNext_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t waitSemaphoreCount {
    set {
      vulkanPINVOKE.VkPresentInfoKHR_waitSemaphoreCount_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPresentInfoKHR_waitSemaphoreCount_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t pWaitSemaphores {
    set {
      vulkanPINVOKE.VkPresentInfoKHR_pWaitSemaphores_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPresentInfoKHR_pWaitSemaphores_get(swigCPtr);
      SWIGTYPE_p_uint64_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint64_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t swapchainCount {
    set {
      vulkanPINVOKE.VkPresentInfoKHR_swapchainCount_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkPresentInfoKHR_swapchainCount_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t pSwapchains {
    set {
      vulkanPINVOKE.VkPresentInfoKHR_pSwapchains_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPresentInfoKHR_pSwapchains_get(swigCPtr);
      SWIGTYPE_p_uint64_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint64_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t pImageIndices {
    set {
      vulkanPINVOKE.VkPresentInfoKHR_pImageIndices_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPresentInfoKHR_pImageIndices_get(swigCPtr);
      SWIGTYPE_p_uint32_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint32_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_VkResult pResults {
    set {
      vulkanPINVOKE.VkPresentInfoKHR_pResults_set(swigCPtr, SWIGTYPE_p_VkResult.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkPresentInfoKHR_pResults_get(swigCPtr);
      SWIGTYPE_p_VkResult ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_VkResult(cPtr, false);
      return ret;
    } 
  }

  public VkPresentInfoKHR() : this(vulkanPINVOKE.new_VkPresentInfoKHR(), true) {
  }

}
