//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VkSampleCountFlagBits {
  VK_SAMPLE_COUNT_1_BIT = 0x00000001,
  VK_SAMPLE_COUNT_2_BIT = 0x00000002,
  VK_SAMPLE_COUNT_4_BIT = 0x00000004,
  VK_SAMPLE_COUNT_8_BIT = 0x00000008,
  VK_SAMPLE_COUNT_16_BIT = 0x00000010,
  VK_SAMPLE_COUNT_32_BIT = 0x00000020,
  VK_SAMPLE_COUNT_64_BIT = 0x00000040
}
