//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VkSharingMode {
  VK_SHARING_MODE_EXCLUSIVE = 0,
  VK_SHARING_MODE_CONCURRENT = 1,
  VK_SHARING_MODE_BEGIN_RANGE = VK_SHARING_MODE_EXCLUSIVE,
  VK_SHARING_MODE_END_RANGE = VK_SHARING_MODE_CONCURRENT,
  VK_SHARING_MODE_RANGE_SIZE = (VK_SHARING_MODE_CONCURRENT-VK_SHARING_MODE_EXCLUSIVE+1),
  VK_SHARING_MODE_MAX_ENUM = 0x7FFFFFFF
}
