//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkSpecializationInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkSpecializationInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkSpecializationInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkSpecializationInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkSpecializationInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_uint32_t mapEntryCount {
    set {
      vulkanPINVOKE.VkSpecializationInfo_mapEntryCount_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkSpecializationInfo_mapEntryCount_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkSpecializationMapEntry pMapEntries {
    set {
      vulkanPINVOKE.VkSpecializationInfo_pMapEntries_set(swigCPtr, VkSpecializationMapEntry.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkSpecializationInfo_pMapEntries_get(swigCPtr);
      VkSpecializationMapEntry ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkSpecializationMapEntry(cPtr, false);
      return ret;
    } 
  }

  public uint dataSize {
    set {
      vulkanPINVOKE.VkSpecializationInfo_dataSize_set(swigCPtr, value);
    } 
    get {
      uint ret = vulkanPINVOKE.VkSpecializationInfo_dataSize_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void pData {
    set {
      vulkanPINVOKE.VkSpecializationInfo_pData_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkSpecializationInfo_pData_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public VkSpecializationInfo() : this(vulkanPINVOKE.new_VkSpecializationInfo(), true) {
  }

}
