//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum VkStencilFaceFlagBits {
  VK_STENCIL_FACE_FRONT_BIT = 0x00000001,
  VK_STENCIL_FACE_BACK_BIT = 0x00000002,
  VK_STENCIL_FRONT_AND_BACK = 0x3
}
