//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkSubmitInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkSubmitInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkSubmitInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkSubmitInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkSubmitInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VkStructureType sType {
    set {
      vulkanPINVOKE.VkSubmitInfo_sType_set(swigCPtr, (int)value);
    } 
    get {
      VkStructureType ret = (VkStructureType)vulkanPINVOKE.VkSubmitInfo_sType_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void pNext {
    set {
      vulkanPINVOKE.VkSubmitInfo_pNext_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkSubmitInfo_pNext_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t waitSemaphoreCount {
    set {
      vulkanPINVOKE.VkSubmitInfo_waitSemaphoreCount_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkSubmitInfo_waitSemaphoreCount_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t pWaitSemaphores {
    set {
      vulkanPINVOKE.VkSubmitInfo_pWaitSemaphores_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkSubmitInfo_pWaitSemaphores_get(swigCPtr);
      SWIGTYPE_p_uint64_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint64_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t pWaitDstStageMask {
    set {
      vulkanPINVOKE.VkSubmitInfo_pWaitDstStageMask_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkSubmitInfo_pWaitDstStageMask_get(swigCPtr);
      SWIGTYPE_p_uint32_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint32_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t commandBufferCount {
    set {
      vulkanPINVOKE.VkSubmitInfo_commandBufferCount_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkSubmitInfo_commandBufferCount_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_p_VkCommandBuffer_T pCommandBuffers {
    set {
      vulkanPINVOKE.VkSubmitInfo_pCommandBuffers_set(swigCPtr, SWIGTYPE_p_p_VkCommandBuffer_T.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkSubmitInfo_pCommandBuffers_get(swigCPtr);
      SWIGTYPE_p_p_VkCommandBuffer_T ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_VkCommandBuffer_T(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t signalSemaphoreCount {
    set {
      vulkanPINVOKE.VkSubmitInfo_signalSemaphoreCount_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkSubmitInfo_signalSemaphoreCount_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t pSignalSemaphores {
    set {
      vulkanPINVOKE.VkSubmitInfo_pSignalSemaphores_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkSubmitInfo_pSignalSemaphores_get(swigCPtr);
      SWIGTYPE_p_uint64_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint64_t(cPtr, false);
      return ret;
    } 
  }

  public VkSubmitInfo() : this(vulkanPINVOKE.new_VkSubmitInfo(), true) {
  }

}
