//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkSwapchainCreateInfoKHR : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkSwapchainCreateInfoKHR(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkSwapchainCreateInfoKHR obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkSwapchainCreateInfoKHR() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkSwapchainCreateInfoKHR(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VkStructureType sType {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_sType_set(swigCPtr, (int)value);
    } 
    get {
      VkStructureType ret = (VkStructureType)vulkanPINVOKE.VkSwapchainCreateInfoKHR_sType_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void pNext {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_pNext_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkSwapchainCreateInfoKHR_pNext_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t flags {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_flags_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkSwapchainCreateInfoKHR_flags_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t surface {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_surface_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64_t ret = new SWIGTYPE_p_uint64_t(vulkanPINVOKE.VkSwapchainCreateInfoKHR_surface_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t minImageCount {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_minImageCount_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkSwapchainCreateInfoKHR_minImageCount_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkFormat imageFormat {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageFormat_set(swigCPtr, (int)value);
    } 
    get {
      VkFormat ret = (VkFormat)vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageFormat_get(swigCPtr);
      return ret;
    } 
  }

  public VkColorSpaceKHR imageColorSpace {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageColorSpace_set(swigCPtr, (int)value);
    } 
    get {
      VkColorSpaceKHR ret = (VkColorSpaceKHR)vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageColorSpace_get(swigCPtr);
      return ret;
    } 
  }

  public VkExtent2D imageExtent {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageExtent_set(swigCPtr, VkExtent2D.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageExtent_get(swigCPtr);
      VkExtent2D ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkExtent2D(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t imageArrayLayers {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageArrayLayers_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageArrayLayers_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t imageUsage {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageUsage_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageUsage_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkSharingMode imageSharingMode {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageSharingMode_set(swigCPtr, (int)value);
    } 
    get {
      VkSharingMode ret = (VkSharingMode)vulkanPINVOKE.VkSwapchainCreateInfoKHR_imageSharingMode_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t queueFamilyIndexCount {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_queueFamilyIndexCount_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkSwapchainCreateInfoKHR_queueFamilyIndexCount_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t pQueueFamilyIndices {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_pQueueFamilyIndices_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkSwapchainCreateInfoKHR_pQueueFamilyIndices_get(swigCPtr);
      SWIGTYPE_p_uint32_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint32_t(cPtr, false);
      return ret;
    } 
  }

  public VkSurfaceTransformFlagBitsKHR preTransform {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_preTransform_set(swigCPtr, (int)value);
    } 
    get {
      VkSurfaceTransformFlagBitsKHR ret = (VkSurfaceTransformFlagBitsKHR)vulkanPINVOKE.VkSwapchainCreateInfoKHR_preTransform_get(swigCPtr);
      return ret;
    } 
  }

  public VkCompositeAlphaFlagBitsKHR compositeAlpha {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_compositeAlpha_set(swigCPtr, (int)value);
    } 
    get {
      VkCompositeAlphaFlagBitsKHR ret = (VkCompositeAlphaFlagBitsKHR)vulkanPINVOKE.VkSwapchainCreateInfoKHR_compositeAlpha_get(swigCPtr);
      return ret;
    } 
  }

  public VkPresentModeKHR presentMode {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_presentMode_set(swigCPtr, (int)value);
    } 
    get {
      VkPresentModeKHR ret = (VkPresentModeKHR)vulkanPINVOKE.VkSwapchainCreateInfoKHR_presentMode_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t clipped {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_clipped_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkSwapchainCreateInfoKHR_clipped_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t oldSwapchain {
    set {
      vulkanPINVOKE.VkSwapchainCreateInfoKHR_oldSwapchain_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64_t ret = new SWIGTYPE_p_uint64_t(vulkanPINVOKE.VkSwapchainCreateInfoKHR_oldSwapchain_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkSwapchainCreateInfoKHR() : this(vulkanPINVOKE.new_VkSwapchainCreateInfoKHR(), true) {
  }

}
