//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkViewport : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkViewport(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkViewport obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkViewport() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkViewport(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public float x {
    set {
      vulkanPINVOKE.VkViewport_x_set(swigCPtr, value);
    } 
    get {
      float ret = vulkanPINVOKE.VkViewport_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      vulkanPINVOKE.VkViewport_y_set(swigCPtr, value);
    } 
    get {
      float ret = vulkanPINVOKE.VkViewport_y_get(swigCPtr);
      return ret;
    } 
  }

  public float width {
    set {
      vulkanPINVOKE.VkViewport_width_set(swigCPtr, value);
    } 
    get {
      float ret = vulkanPINVOKE.VkViewport_width_get(swigCPtr);
      return ret;
    } 
  }

  public float height {
    set {
      vulkanPINVOKE.VkViewport_height_set(swigCPtr, value);
    } 
    get {
      float ret = vulkanPINVOKE.VkViewport_height_get(swigCPtr);
      return ret;
    } 
  }

  public float minDepth {
    set {
      vulkanPINVOKE.VkViewport_minDepth_set(swigCPtr, value);
    } 
    get {
      float ret = vulkanPINVOKE.VkViewport_minDepth_get(swigCPtr);
      return ret;
    } 
  }

  public float maxDepth {
    set {
      vulkanPINVOKE.VkViewport_maxDepth_set(swigCPtr, value);
    } 
    get {
      float ret = vulkanPINVOKE.VkViewport_maxDepth_get(swigCPtr);
      return ret;
    } 
  }

  public VkViewport() : this(vulkanPINVOKE.new_VkViewport(), true) {
  }

}
