//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VkWriteDescriptorSet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VkWriteDescriptorSet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VkWriteDescriptorSet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VkWriteDescriptorSet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vulkanPINVOKE.delete_VkWriteDescriptorSet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VkStructureType sType {
    set {
      vulkanPINVOKE.VkWriteDescriptorSet_sType_set(swigCPtr, (int)value);
    } 
    get {
      VkStructureType ret = (VkStructureType)vulkanPINVOKE.VkWriteDescriptorSet_sType_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void pNext {
    set {
      vulkanPINVOKE.VkWriteDescriptorSet_pNext_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkWriteDescriptorSet_pNext_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t dstSet {
    set {
      vulkanPINVOKE.VkWriteDescriptorSet_dstSet_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64_t ret = new SWIGTYPE_p_uint64_t(vulkanPINVOKE.VkWriteDescriptorSet_dstSet_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t dstBinding {
    set {
      vulkanPINVOKE.VkWriteDescriptorSet_dstBinding_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkWriteDescriptorSet_dstBinding_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t dstArrayElement {
    set {
      vulkanPINVOKE.VkWriteDescriptorSet_dstArrayElement_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkWriteDescriptorSet_dstArrayElement_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t descriptorCount {
    set {
      vulkanPINVOKE.VkWriteDescriptorSet_descriptorCount_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(vulkanPINVOKE.VkWriteDescriptorSet_descriptorCount_get(swigCPtr), true);
      if (vulkanPINVOKE.SWIGPendingException.Pending) throw vulkanPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VkDescriptorType descriptorType {
    set {
      vulkanPINVOKE.VkWriteDescriptorSet_descriptorType_set(swigCPtr, (int)value);
    } 
    get {
      VkDescriptorType ret = (VkDescriptorType)vulkanPINVOKE.VkWriteDescriptorSet_descriptorType_get(swigCPtr);
      return ret;
    } 
  }

  public VkDescriptorImageInfo pImageInfo {
    set {
      vulkanPINVOKE.VkWriteDescriptorSet_pImageInfo_set(swigCPtr, VkDescriptorImageInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkWriteDescriptorSet_pImageInfo_get(swigCPtr);
      VkDescriptorImageInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkDescriptorImageInfo(cPtr, false);
      return ret;
    } 
  }

  public VkDescriptorBufferInfo pBufferInfo {
    set {
      vulkanPINVOKE.VkWriteDescriptorSet_pBufferInfo_set(swigCPtr, VkDescriptorBufferInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkWriteDescriptorSet_pBufferInfo_get(swigCPtr);
      VkDescriptorBufferInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new VkDescriptorBufferInfo(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t pTexelBufferView {
    set {
      vulkanPINVOKE.VkWriteDescriptorSet_pTexelBufferView_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = vulkanPINVOKE.VkWriteDescriptorSet_pTexelBufferView_get(swigCPtr);
      SWIGTYPE_p_uint64_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_uint64_t(cPtr, false);
      return ret;
    } 
  }

  public VkWriteDescriptorSet() : this(vulkanPINVOKE.new_VkWriteDescriptorSet(), true) {
  }

}
